config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweeties#index'
  resources :tweeties
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweety.rb
class Tweety < ApplicationRecord
  validates :message, presence: true, length: { maximum: 250 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweeties_controller.rb
class TweetiesController < ApplicationController
  before_action :set_tweety, only: %i[show edit update destroy]

  # GET /tweeties
  # GET /tweeties.json
  def index
    @tweeties = Tweety.all
    @tweety = Tweety.new
  end

  # GET /tweeties/1
  # GET /tweeties/1.json
  def show; end

  # GET /tweeties/new
  def new
    @tweety = Tweety.new
  end

  # GET /tweeties/1/edit
  def edit; end

  # POST /tweeties
  # POST /tweeties.json
  def create
    @tweety = Tweety.new(tweety_params)

    respond_to do |format|
      if @tweety.save
        format.html { redirect_to @tweety, notice: 'Tweety was successfully created.' }
        format.json { render :show, status: :created, location: @tweety }
      else
        format.html { render :new }
        format.json { render json: @tweety.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeties/1
  # PATCH/PUT /tweeties/1.json
  def update
    respond_to do |format|
      if @tweety.update(tweety_params)
        format.html { redirect_to @tweety, notice: 'Tweety was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweety }
      else
        format.html { render :edit }
        format.json { render json: @tweety.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeties/1
  # DELETE /tweeties/1.json
  def destroy
    @tweety.destroy
    respond_to do |format|
      format.html { redirect_to tweeties_url, notice: 'Tweety was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweety
    @tweety = Tweety.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweety_params
    params.require(:tweety).permit(:message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeties_helper.rb
module TweetiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittier</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://kit.fontawesome.com/9b6ee7cdf7.js' %>
  </head>

  <body>
    <nav class="navbar is-info" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class: "nav-item has-text-white is-size-4", role: "button" do %>
          <h1 class="my-2 ml-5" >Twittier</h1>
        <% end %>

        <%= link_to root_path, class: "navbar-burger burger", role: "button", "aria-label" => "menu", "aria-expanded" => "false", "data-target" => "navbarBasicExample" do %>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        <% end %>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <%= link_to new_tweety_path, class: "button is-light has-text-info" do %>
                <strong>New tweety</strong>
              <% end %>
              <%= link_to nil, class: "button is-info has-text-white" do %>
                Log in
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav> 

    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>  

    <%= yield %>
  </body>
</html>

app/views/tweeties/_feed.html.erb
<article class="media">
  <%= form_with model: @tweety, local: true do |form| %>
  
    <% if @tweety.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tweety.errors.count, "error") %> prohibited this tweety from being saved:</h2>
  
        <ul>
          <% @tweety.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <div class="control">
        <%= form.text_area :message, class: 'textarea' %>
      </div>
    </div>
  
    <div class="field">
      <div class="control">
        <%= form.submit 'Post a tweety', class: 'button is-info' %>
      </div>
    </div>
 
  <% end %>
</article>


<% @tweeties.each do | tweety | %>
  <article class="media">
    <figure class="media-left">
      <p class="image is-64x64 ">
        <img class="tweety-profile" src="https://bulma.io/images/placeholders/128x128.png">
      </p>
    </figure>
    <div class="media-content">
      <div class="content">
        <div class="content-title"><strong>John Smith</strong> <small>@johnsmith</small> <small>31m</small></div>
        <p>
          <%= tweety.message %>
        </p>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
          <%= link_to tweety_path(tweety), class: "level-item" do %>
            <span class="icon is-small"><i class="fas fa-link"></i></span>
          <% end %>
          <%= link_to edit_tweety_path(tweety), class: "level-item" do %>
            <span class="icon is-small"><i class="fa fa-pencil"></i></span>
          <% end %>
          <%= link_to tweety_path(tweety), method: :delete, data: { confirm: "Do you really want to delete this tweety?" }, class: "level-item" do %>
            <span class="icon is-small"><i class="fa fa-trash-o"></i></span>
          <% end %>
        </div>
      </nav>
    </div>
  </article>
<% end %>

app/views/tweeties/_form.html.erb
<%= form_with(model: tweety, local: true) do |form| %>
  <% if tweety.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweety.errors.count, "error") %> prohibited this tweety from being saved:</h2>

      <ul>
        <% tweety.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweeties/_profile.html.erb
<div class="card">
  <div class="card-image">
    <figure class="image is-3by1">
      <img src="https://bulma.io/images/placeholders/720x240.png" alt="Placeholder image">
    </figure>
  </div>
  <div class="card-content">
    <figure class="image is-48x48">
      <img class="tweety-profile" src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
    </figure>
    <div class="content">
      <p class="title is-4">John Smith</p>
      <p class="subtitle is-6">@johnsmith</p>
    </div>
    <div class="content">
    </div>
  </div>
</div>

app/views/tweeties/_suggestions.html.erb
<nav class="panel">
  <p class="panel-heading">
    Who to follow
  </p>

  <div class="f-list py-2 px-2">
    <article class="level">
      <div class="level-left">
        <p class="image is-48x48">
          <img class="tweety-profile" src="https://bulma.io/images/placeholders/128x128.png">
        </p>
        <div class="content pl-2">
          <strong>John Smith</strong> <br> <small>@johnsmith</small>
        </div>
      </div>
      <div class="level-right">
        <%= link_to nil, 'follow', class: 'button is-info is-small' %>
      </div>
    </article>
    <article class="level">
      <div class="level-left">
        <p class="image is-48x48">
          <img class="tweety-profile" src="https://bulma.io/images/placeholders/128x128.png">
        </p>
        <div class="content pl-2">
          <strong>John Smith</strong> <br> <small>@johnsmith</small>
        </div>
      </div>
      <div class="level-right">
        <%= link_to nil, 'follow', class: 'button is-info is-small' %>
      </div>
    </article>
    <article class="level">
      <div class="level-left">
        <p class="image is-48x48">
          <img class="tweety-profile" src="https://bulma.io/images/placeholders/128x128.png">
        </p>
        <div class="content pl-2">
          <strong>John Smith</strong> <br> <small>@johnsmith</small>
        </div>
      </div>
      <div class="level-right">
        <%= link_to nil, 'follow', class: 'button is-info is-small' %>
      </div>
    </article>
    <article class="level">
      <div class="level-left">
        <p class="image is-48x48">
          <img class="tweety-profile" src="https://bulma.io/images/placeholders/128x128.png">
        </p>
        <div class="content pl-2">
          <strong>John Smith</strong> <br> <small>@johnsmith</small>
        </div>
      </div>
      <div class="level-right">
        <%= link_to nil, 'follow', class: 'button is-info is-small' %>
      </div>
    </article>
    <article class="level">
      <div class="level-left">
        <p class="image is-48x48">
          <img class="tweety-profile" src="https://bulma.io/images/placeholders/128x128.png">
        </p>
        <div class="content pl-2">
          <strong>John Smith</strong> <br> <small>@johnsmith</small>
        </div>
      </div>
      <div class="level-right">
        <%= link_to nil, 'follow', class: 'button is-info is-small' %>
      </div>
    </article>
  
  </div>
</nav>

app/views/tweeties/edit.html.erb
<h1>Editing Tweety</h1>

<%= render 'form', tweety: @tweety %>

<%= link_to 'Show', @tweety %> |
<%= link_to 'Back', tweeties_path %>

app/views/tweeties/index.html.erb
<% 
=begin %>
<p id="notice"><%= notice %></p>

<h1>Tweeties</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweeties.each do |tweety| %>
      <tr>
        <td><%= tweety.message %></td>
        <td><%= link_to 'Show', tweety %></td>
        <td><%= link_to 'Edit', edit_tweety_path(tweety) %></td>
        <td><%= link_to 'Destroy', tweety, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweety', new_tweety_path %>
<%
=end %>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <%= render "profile"%>
      </div>
      <div class="column is-half">
        <%= render "feed"%>
      </div>
      <div class="column">
        <%= render "suggestions"%>
      </div>
    </div>
  </div>
</section>

app/views/tweeties/new.html.erb
<h1>New Tweety</h1>

<%= render 'form', tweety: @tweety %>

<%= link_to 'Back', tweeties_path %>

app/views/tweeties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweety.message %>
</p>

<%= link_to 'Edit', edit_tweety_path(@tweety) %> |
<%= link_to 'Back', tweeties_path %>